services:
  app:
    build:
      context: .
    container_name: hubspot-integration-api
    environment:
      HUBSPOT_CLIENT_ID: <CLIENT_ID>
      HUBSPOT_CLIENT_SECRET: <CLIENT_SECRET>
      REDIRECT_URL: https://<NGROK_URL>
    ports:
      - "8080:8080"